---
title: "p8105_hw5_ht2607"
output: html_document
date: "2023-11-04"
---

### Setting Up 

```{r setup, include=FALSE}
library(tidyverse)
library(ggridges)
library(patchwork)

library(p8105.datasets)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

### Question 1

## Homicides in Baltimore

```{r}
baltimore_df = 
  read_csv("q1data/homicide-data.csv") |> 
  filter(city == "Baltimore") |> 
  mutate(
    resolved = as.numeric(disposition == "Closed by arrest"),
    victim_age = as.numeric(victim_age)
  ) |> 
  select(resolved, victim_age, victim_race, victim_sex)
```


fitting a logistic regression

```{r}
fit_logistic = 
  baltimore_df |> 
  glm(
    resolved ~ victim_age + victim_race + victim_sex, 
    data = _, 
    family = binomial())
```

look at model results

```{r}
fit_logistic |> 
  broom::tidy() |> 
  mutate(OR = exp(estimate)) |> 
  select(term, estimate, OR)
```


```{r}
baltimore_df |> 
  count(victim_race)

```

### Question 2

```{r}
library(purrr)
library(readr)

# Specify the directory where your CSV files are located
directory_path = "/Users/cindytseng/Desktop/p8105_hw5_ht2607/data/"

# List all CSV files
csv_files_df =
  list.files(directory_path, pattern = "\\.csv$", full.names = TRUE)

# Create a dataframe to store filenames
file_df = 
  tibble(
    files = list.files(directory_path),
    path = str_c(directory_path, files)
  ) |> 
  mutate(data = map(path, read_csv)) |> 
  unnest()

# Extract subject ID and arm from filenames
file_df <- file_df |> 
  mutate(
    subject_id = str_extract(files, "\\d+"), # Extract numerical subject ID
    arm = str_extract(files, "con|exp") # Extract arm information
  )

# Unnest the data and select relevant columns
exp_con_tidy_df <- file_df |> 
  pivot_longer(
    week_1:week_8,
    names_to = "week",
    names_prefix = "week_",
    values_to = "values"
  ) |> 
  select(subject_id, arm, week, values) |>
  mutate(week = as.numeric(week))
  

# Create a spaghetti plot
ggplot(exp_con_tidy_df, aes(x = week, y = values, color = subject_id)) + 
  facet_grid(. ~ arm) +
  geom_line() +
  labs(title = "Spaghetti Plot of Longitudinal Data",
       x = "Week",
       y = "Observation",
       color = "Arm") +
  theme(legend.position = "bottom")

```

### Question 3

```{r}
library(tidyverse)

n <- 30
sigma <- 5
alpha <- 0.05
mu_s <- c(0, 1, 2, 3, 4, 5, 6)

set.seed(1)

# creating a function and setting up 
sim_mean_sd = function(n = 30, mu, sigma = 5, alpha = 0.05) {
  
  sim_data = tibble(
    x = rnorm(n, mean = mu, sd = sigma),
  )
  
  sim_data |> 
    summarize(
      mu_hat = mean(x),
      sigma_hat = sd(x)
    )
}


```

```{r}
# creating a function for the t-test
t_test_function <- function(n, mu, sigma) {
  sample <- rnorm(n, mean = mu, sd = sigma)
  test_result <- t.test(sample, mu = 0)
  broom::tidy(test_result)
}
```

```{r}
results <- tibble(mu = numeric(), mu_hat = numeric(), p_value = numeric(), reject = logical())
```


```{r}
# doing literation for 5000 times (random sampling for 5000 times)
for (mu in mu_s) {
  for (i in 1:5000) {
    sim_results <- sim_mean_sd(n, mu, sigma)
    t_test_results <- t_test_function(n, mu, sigma)
    results <- results |> 
      add_row(mu = mu, 
              mu_hat = sim_results$mu_hat, 
              p_value = t_test_results$p.value, 
              reject = t_test_results$p.value < alpha)
  }
}
```

```{r}
power_results <- results |> 
  group_by(mu) |> 
  summarise(power = mean(reject), 
            avg_mu_hat = mean(mu_hat), 
            avg_mu_hat_rejected = mean(mu_hat[reject]))
```


```{r}
# Plotting power against true values of μ
power_plot <- power_results |> 
  ggplot(aes(x = mu, y = power)) +
  geom_point() +
  geom_line() +
  labs(title = "Power vs. True Value of μ",
       x = "True Value of μ",
       y = "Power")

# Display the plots
power_plot
```



```{r}
# Plotting average estimate of μ̂ against true values of μ
avg_estimate_plot <- power_results |>  
  ggplot(aes(x = mu)) +
  geom_point(aes(y = avg_mu_hat, 
                 color = "Average Estimate"), 
                shape = 1) +  
  geom_line(aes(y = avg_mu_hat, 
                color = "Average Estimate")) +
  geom_point(aes(y = avg_mu_hat_rejected, 
                 color = "Conditional Average Estimate"), shape = 2) +
  geom_line(aes(y = avg_mu_hat_rejected, 
                color = "Conditional Average Estimate"), linetype = "dashed") +
  labs(
    title = "Average Estimated Mean vs. True Mean",
    x = "True Mean (mu)",
    y = "Average Estimated Mean",
    color = "mu_hat"
  ) +
  scale_color_manual(
    values = c("Average Estimate" = "blue", "Conditional Average Estimate" = "red")
  ) +
  theme_minimal() +
  theme(legend.position = "bottom")

# Display the plots
avg_estimate_plot

```





